#!/bin/bash
# -*- Mode:Shell; indent-tabs-mode:nil; tab-width -*-
#
# Copyright 2022 Kenneth Loafman <kenneth@loafman.com>
#
# This file is part of duplicity.
#
# Duplicity is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# Duplicity is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with duplicity; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

set -e

if [ "$#" -ne 0 ]; then
    echo "usage: makechangelog"
    exit 2
fi

gitchangelog > CHANGELOG.md
CNT=`git status --porcelain | tee /dev/stderr | grep -v " M CHANGELOG.md" | wc -l`
if [ $CNT -ne 0 ]; then
    echo "*** REPO DIRTY, REFUSING TO COMMIT ***"
    exit 1
fi

git commit -m"Update changelog." -m"[skip ci]" CHANGELOG.md
git push
